blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/RakSrinaNa/ChannelPointsMiner/discussions
    about: Got a more generic thing to say that isn't an issue or feature request or you need support? Start a discussion here
